### ISSUE TITLE
NAM WEB SDK 사용 시 같은 페이지에 동일한 인벤토리 노출

### ISSUE THREAD

**Issue by raejoonee** [naver/nam-sdk-web#10]
안녕하세요.

NAM WEB SDK를 사용하면서, 같은 페이지에 동일한 adSlotInfo를 넣어서 2개 이상의 컴포넌트를 렌더링하고자 하는데, 하나만 광고가 송출되는 현상이 있어서 이에 문의드립니다.

혹시 같은 페이지에 동일한 adSlotInfo를 넣어서 2개 이상의 컴포넌트를 사용할 수 있나요? 만약 가능하다면, 방법에 대해서 조언 부탁드려도 될까요? 감사합니다.

**Comment by jongguk-park** [comment]
안녕하세요. adSlotInfo 객체를 중복 사용 시 adSlotElementId가 포함되어 있다면 중복된 adSlotElementId로 인식하여 최초 설정된 광고 슬롯 기준으로만 광고 호출이 동작할 수 있을 듯 합니다.

아래의 중복 제어 광고 적용과 같이 광고 슬롯 여러개를 동일 adSlotInfo 객체를 통해 생성한다면 adSlotElementId 없이 adUnitId만 설정하도록 수정 부탁드립니다. 

https://naver.github.io/nam-sdk-guide/web/examples/dedup_persist

**Comment by raejoonee** [comment]
감사합니다, 문제 해결에 큰 도움이 되었습니다. 이슈 닫겠습니다.
