### ISSUE TITLE
광고 미노출 현상 문의

### ISSUE THREAD

**Issue by YulHeon** [naver/nam-sdk-web#11]
안녕하세요 플레이스여행플랫폼 김율헌입니다.

현재 nam sdk web 를 이용해서 GFD 광고 서빙 테스트를 진행중에 문의가 있어서 연락드립니다.

window.gladsdk.cmd에 정상적으로 하단코드가 push된것을 콘솔로그 및 디버깅을하여 확인하였는데
광고가 노출(https://beta-nam.veta.naver.com/gfp/v1 요청도 X)가 안되는현상이 가끔씩 발생하는데 가능한 상황인지 문의드립니다.

모든 광고가 노출안되는 상황은 cmd가 array 객체로 sdk가 init 되기전에 호출시에 발생했습니다. 
그리고 gfp-core.js가 캐싱 되어있을때 발생하는것처럼 보입니다. (disable cache 옵션을 키고 사용하면 백프로 정상 동작)

```js
      gladsdk.cmd.push(() => {
        const prevAdSlot = gladsdk.findAdSlot(adSlotElementId);
        if (prevAdSlot) {
          gladsdk.destroyAdSlots([prevAdSlot]);
        }
        gladsdk.defineAdSlot(Object.assign({ adSlotElementId }, adSlotInfo));
        gladsdk.displayAd(adSlotElementId);
      });
    }
```

**Comment by YulHeon** [comment]
https://naver.github.io/nam-sdk-guide/web/trouble_shooting#2-gladsdk-%EC%8A%A4%EC%BD%94%ED%94%84-%EC%B2%B4%EC%9D%B4%EB%8B%9D%EC%9C%BC%EB%A1%9C-%EC%9D%B8%ED%95%9C-%EB%AC%B8%EC%A0%9C

gladsdk 스코프 체이닝으로 인한 문제가 문제 였습니다. 현재 해결되었습니다. 감사합니다

**Comment by jongguk-park** [comment]
@YulHeon 확인이 늦었습니다. 우선 가이드 문서 기준으로 이슈 해결이 되셨다고 확인해주셔서 감사합니다.
추가 안내드릴 내용이 있는데요. 가이드 문서에도 안내가 되어있는 내용인데 다음번 사내 서비스 문의는 내부 문의 채널로 전달 부탁드리겠습니다.
현재 해당 깃허브 채널의 경우 외부 매체용 개발 문의 대응을 위해 운영하고 있습니다. 

감사합니다.
