### ISSUE TITLE
nam sdk event handler 관련 메서드 추가 문의

### ISSUE THREAD

**Issue by cyjo9603** [naver/nam-sdk-web#13]
안녕하세요.
플레이스 여행 플랫폼 조찬영입니다.

현재 nam sdk를 통해 서비스에 광고를 노출하고 있는데, 특정 광고가 노출되었을 때 / 노출되지 않았을때 를 기준으로
노출되었을때는 해당 영역을 wrapping하고 있는 ui를 보여주고, 노출되지 않았을때는 wrapping하고 있는 ui도 숨겨주는 기능을 사용하고 있습니다.

그런데 현재 nam sdk api상 addEventListener로는 각각의 광고 영역에 대한 event handler는 등록할 순 없고 sdk 전체적인 event handler만 등록 가능한것으로 보입니다.
이벤트를 지우는것도 개별 event handler를 지우는 것이 아닌 모든 event handler를 지우는 api만 제공하고 있고요.

저희는 리액트 기반으로 컴포넌트 구조에서 sdk를 사용하고 있기 때문에, 개별 컴포넌트에 대한 광고 노출 여부를 event handler를 받아오는게 필요한데, 현 구조상으로는 sdk에서 제공해주는 api만으로는 불가능해서, 자체적으로 내부 queue에 event handler를 체이닝해서 실행해주는 형태로 작성하고 있습니다.

아무래도, 저희가 wrapping한 구조보다는 sdk 자체에서 네이티브 기능으로 지원을 해주면 좋을것 같은데, 혹시 다음 내용에 대해 지원하실 계획이 있으실까요?

**Comment by jongguk-park** [comment]
@cyjo9603 안녕하세요. 네이버 서비스 적용건은 가이드 문서에 명시된대로 [사내 문의 채널](https://oss.navercorp.com/da-ssp-app-sdk/bts/issues/new/choose)로 전달 부탁드립니다.
