### ISSUE TITLE
광고 파라미터 설정 가이드 업데이트 요청

### ISSUE THREAD

**Issue by youngman71** [naver/nam-sdk-web#2]
광고 파라미터 설정 > 광고ID

iv값에 안드로이드 app-set-id 적용에 대해서 가이드 내용 업데이트 요청 드립니다.

- ai : ADID (안드로이드 GAID, iOS IDFA), e.g.) 001bd666-dbc0-4e3c-900f-e2bbb1668c38
- iv : identifierForVendor, iOS IDFA를 대체할 수 있는 identifier로 등록한 서비스 Vendor ID, e.g.) com.navercorp 을 UUID 형태로 추출한 값

**Comment by sungwook-kwon** [comment]
@youngman71 님 안녕하세요.

웹앱의 경우,
NAM WEB SDK 로 App 의 `adid / ifa` 또는 `app-set-id / ifv` 값을 전달해 주시면 되겠습니다.
(optional param 으로 획득 가능하실때 전달)

- Android
  - **ai** - adid 전달
  - **iv** - app-set-id 전달
- iOS
  - **ai** - ifa 전달
  - **iv** - ifv 전달
  
```js
<script>
  window.gladsdk.cmd.push(function () {
    var adSlotInfo = {
      adUnitId: 'WEB_nw_banner-N345765840',
      adSlotElementId: 'division',
      ai: '001bd666-dbc0-4e3c-900f-e2bbb1668c38', // optional
      iv: '58F36556-19FD-445B-AF3A-C6D86B15D56C', // optional
      yob: 1988, // year of birth, 4 digit number
      gender: 'M', // gender, 'M':male, 'F': female, 'O': unknown
      uct: 'KR', // user country
      uid: 'user id', // publisher user identifier
      customParam: {}, // custom parameter
    };
    window.gladsdk.defineAdSlot(adSlotInfo);
  });
</script>
```
