### ISSUE TITLE
NAM-SDK-WEB을 퍼블리셔로 사용하고 싶은데 어떻게 해야하나요?

### ISSUE THREAD

**Issue by JeremyDev87** [naver/nam-sdk-web#3]
NAM-SDK-WEB을 퍼블리셔로 사용하고 싶은데 어떻게 해야하나요?

admin 또는 console의 URL 과 가입 절차 부탁드립니다. 
관련된 안내 문서가 있다면 제공 부탁드리겠습니다.

관련하여 필요하신 부분이 있다면 해당 이슈의 스레드나 jeremy@classting.com 으로 연락 부탁드립니다. 
감사합니다.

**Comment by sungwook-kwon** [comment]
별도 채널로 답변이 된 부분이라 해당 이슈 클로즈 하겠습니다.
감사합니다.
