### ISSUE TITLE
`AdBlock found` error 문의

### ISSUE THREAD

**Issue by jaryapp** [naver/nam-sdk-web#4]
sdk에서 `AdBlock found` 에러가 발생해서 문의드립니다.
![image](https://user-images.githubusercontent.com/49256790/231044203-fa14b75f-00ab-497d-9e0d-f6c6313af683.png)

`AdBlock`이 설치된 브라우저에서 발생하는 에러가 맞을까요?
브라우저에 `AdBlock`이 설치되지 않았는데 발생하고 있습니다

**Comment by jongguk-park** [comment]
안녕하세요. 네이버 박종국입니다. 문의 주신 이슈 재현 가능한 테스트 환경 공유주시면 확인해보겠습니다.
다만 AdBlock 판별의 경우 저희도 AdBlock 설치 되었을때 발생할수 있는 케이스를 기준으로 추정하여 에러 처리가 되는 상태라 문의주신 것처럼
잘못 판별되어 전달될 수는 있을것 같습니다.
