### ISSUE TITLE
에러 코드 문의

### ISSUE THREAD

**Issue by joshua1988** [naver/nam-sdk-web#6]
안녕하세요, 이번에 광고 SDK를 붙이는 작업을 하고 있는데 페이지 로딩시에 간헐적으로 다음과 같은 에러 코드가 발생합니다.

#### SDK의 `onError` 핸들러의 `error` 파라미터

<img width="338" alt="image" src="https://github.com/naver/nam-sdk-web/assets/3272748/30fa5ef2-e3a1-4c9f-bdf8-8e9046dd2463">

혹시 저희가 참고할만한 에러코드 유형별 가이드가 있을까요? :)
감사합니다.

**Comment by jongguk-park** [comment]
@joshua1988 안녕하세요. 별도 문의 채널로 답변드리겠습니다.
