### ISSUE TITLE
배너 크기 조절 문의

### ISSUE THREAD

**Issue by Gunn-Tmobi** [naver/nam-sdk-web#9]
제공해주신 가이드 문서 https://naver.github.io/nam-sdk-guide/web/common/get_started (링크가 잘못연결된 것 같습니다)
통해서 확인해본 결과
따로 배너 크기를 조절할 수 있는 api혹은 config가 없을까요?

sdk내부 ad-element안에 a태그에서 size_ 클래스를 통해서 크기 조절이 되는것으로 보이는데
따로 크기를 사용자가 조절할 수는 없을까요?

**Comment by jongguk-park** [comment]
별도로 안내가 되어있던 내용인데 댓글로도 남깁니다.
https://naver.github.io/nam-sdk-guide/web/basic/get_started 기본 가이드 링크는 여기로 참고 부탁드립니다.

네이티브 광고에 대해서는 현재는 저희 쪽에서 매체쪽 광고 크기에 맞춰 커스텀 visual 형태로 제공해드리고 있습니다.
티맵의 경우 80px, 60px 기준으로 광고 영역이 각각 제공되고있어 그에 맞춘 사이즈 기준으로 내부 visual 코드에 높이값 설정을 위한 처리가 적용되어 있습니다. 기본적으로는 해당 스마트채널 visual 유형에 대해서는 80px 기준이 기본 visual이고 60px 기준이 커스텀 형태라고 봐주시면 됩니다.

매체에서 직접 네이티브 광고에 대한 visual 코드 구성을 하도록 공식적으로 지원하고 있지는 않아서 네이티브 광고에 대해서는 현재처럼 저희쪽 문의 채널을 통해 요청을 주시면 됩니다. 추후 해당 운영 기준이 변경되면 해당 채널을 통해 변경 내용에 대해 한번 더 공유드릴 수 있을 듯 합니다.

**Comment by jongguk-park** [comment]
@zb-sj 안녕하세요. 현재 스마트채널 이미지형 소재에 대해서는 60px 커스텀 대응 소재가 노출중인 것으로 보입니다. 다만 추가 문의주신 캐로셀형 소재의 경우 별도로 커스텀 요청이 인입된 이력이 없어서 기본 프리셋 유형 소재로 운영중인게 아닌가 싶습니다.

저희쪽 기획 담당자분 통해 캐로셀형 유형에 대한 소재 노출 스펙으로 60px 기준으로 대응 요청을 주신게 맞는지 궁금합니다.
캐로셀형에 대해서도 해당 사이즈 대응을 원하시는게 맞다면 내부에서 캐로셀 유형에 대해 60px 커스텀 대응이 가능한지 확인후에 가능하다면 커스텀 대응 지원이 가능할것 같습니다.

추가적으로 예시로 전달주신 코드에서 `width:375px;height:210px`로 광고 영역 크기를 따로 잡아주신 이유가 있을까요? 
네이티브 소재에 대한 사이즈 대응은 저희 NAM admin에 등록된 네이티브 visual 코드를 기준으로 마크업 대응을 해주고 있어서 매체측에서 특별한 이유가 없다면 크기를 저렇게 잡아주실 이유가 없을듯 합니다. 특히나 높이값을 210px로 div 요소에 잡으면 실제 iframe 크기보다 훨씬 크게 잡힐거라 빈공백 영역이 노출될 우려가 있어보입니다.

**Comment by jongguk-park** [comment]
@zb-sj 저희 기획 담당자분께도 관련 이슈 추가로 문의해봤는데요. 이미지형에서 60px 커스텀으로 대응 요청을 주셨던 이력이 있으나 현재는 단순 테스트 유닛에서만 설정되있고 실제 운영은 80px 스펙으로 운영중이라고 합니다.
저희 담당자분 말씀으론 TMAP측이랑 스마트채널 높이를 80px 기준으로 협의하셨던 것으로 확인해주셨는데요. 이 부분이 맞는지 다시한번 확인 부탁드립니다.

혹시라도 별도의 커스텀 대응이 필요한 이슈라면 개발 이슈라기 보다는 운영 관련 문의로 보여 업무용 슬렉 채널을 통해 저희 NAM 담당자에게 문의를 부탁드립니다.

**Comment by zb-sj** [comment]
@jongguk-park 빠른 답변 감사합니다!
제 설명이 부족하여 TMAP 담당자로 오해하고 답변해 주신 듯합니다. 😅

그럼에도 불구하고 상세한 답변 덕분에 운영 관련 이슈를 명확히 이해할 수 있었습니다.
NAM 담당자와 연락이 닿을 수 있도록 저희 PO에게 내용을 전달하겠습니다.
